# Generated by Django 5.2.1 on 2026-05-05 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('content', models.TextField()),
                ('date', models.DateTimeField()),
                ('price', models.IntegerField()),
                ('mojodi', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='')),
                ('emial', models.EmailField(max_length=254)),
            ],
        ),
    ]
