# Generated by Django 5.2.1 on 2026-06-02 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_post_order_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Futured',
            field=models.BooleanField(default=False),
        ),
    ]
