# Generated by Django 5.2.1 on 2026-06-02 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_post_futured'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Futured',
            new_name='Featured',
        ),
    ]
