# Generated by Django 5.2.1 on 2026-06-02 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_futured_post_featured'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Featured',
            new_name='featured',
        ),
    ]
