# Generated by Django 5.2.1 on 2026-06-12 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_category_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='discount',
            field=models.IntegerField(default=0),
        ),
    ]
