# Generated by Django 5.2.1 on 2026-06-12 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_post_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='discount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='price',
            field=models.PositiveIntegerField(verbose_name='قیمت تومان'),
        ),
    ]
