# Generated by Django 5.2.1 on 2026-06-13 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_post_discount_alter_post_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='show_in_new',
            field=models.BooleanField(default=False),
        ),
    ]
