# Generated by Django 5.2.1 on 2026-06-20 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_post_slug'),
        ('home', '0011_product'),
    ]

    operations = [
    ]
