# Generated by Django 5.2.1 on 2026-06-24 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار'), ('paid', 'پرداخت شده'), ('sent', 'ارسال شده'), ('done', 'تحویل داده شده'), ('cancelled', 'لغو شده')], default='pending', max_length=20),
        ),
    ]
