# Generated by Django 5.2.1 on 2026-06-27 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'پرداخت نشده'), ('paid', 'پرداخت شده')], default='unpaid', max_length=20),
        ),
    ]
