# Generated by Django 5.2.1 on 2026-06-30 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_order_payment_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product')},
        ),
    ]
