# Generated by Django 5.2.1 on 2026-07-04 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_alter_cartitem_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='emial',
            new_name='email',
        ),
    ]
