# Generated by Django 5.2.1 on 2026-07-11 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='message_type',
            field=models.CharField(choices=[('general', 'سوال عمومی'), ('order', 'مشکل سفارش')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='order_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
