# Generated by Django 5.2.1 on 2026-07-13 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_ticketreply'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='status',
            field=models.CharField(choices=[('open', 'باز'), ('answered', 'پاسخ داده شده'), ('closed', 'بسته شده')], default='open', max_length=20),
        ),
    ]
