# Generated by Django 5.2.1 on 2026-07-13 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_adminnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='admin_seen',
            field=models.BooleanField(default=False),
        ),
    ]
