# Generated by Django 5.2.1 on 2026-07-16 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_productcolor_productimage_productsize'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfumeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.CharField(max_length=20)),
                ('longevity', models.CharField(choices=[('کم', 'کم'), ('متوسط', 'متوسط'), ('زیاد', 'زیاد'), ('خیلی زیاد', 'خیلی زیاد')], max_length=20)),
                ('season', models.CharField(choices=[('بهار', 'بهار'), ('تابستان', 'تابستان'), ('پاییز', 'پاییز'), ('زمستان', 'زمستان'), ('چهار فصل', 'چهار فصل')], max_length=20)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfume_detail', to='home.post')),
            ],
        ),
    ]
