# Generated by Django 5.2.1 on 2026-07-16 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_perfumedetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfumedetail',
            name='season',
            field=models.CharField(choices=[('بهار', 'بهار'), ('تابستان', 'تابستان'), ('پاییز', 'پاییز'), ('زمستان', 'زمستان'), ('بهار و تابستان', 'بهار و تابستان'), ('پاییز و زمستان', 'پاییز و زمستان'), ('چهار فصل', 'چهار فصل')], max_length=20),
        ),
    ]
