# Generated by Django 5.2.1 on 2026-07-17 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_alter_perfumedetail_season'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='MHS Store', max_length=100)),
                ('admin_email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('instagram', models.URLField(blank=True)),
                ('telegram', models.URLField(blank=True)),
                ('about', models.TextField(blank=True)),
                ('maintenance', models.BooleanField(default=False)),
                ('registration', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='perfumedetail',
            name='season',
            field=models.CharField(choices=[('بهار', 'بهار'), ('تابستان', 'تابستان'), ('پاییز', 'پاییز'), ('زمستان', 'زمستان'), ('بهار و تابستان', 'بهار و تابستان'), ('پاییز و زمستان', 'پاییز و زمستان'), ('چهار فصل', 'چهار فصل'), ('پاییز و بهار', 'پاییز و بهار')], max_length=20),
        ),
    ]
