# Generated by Django 5.2.1 on 2026-07-17 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_sitesettings_favicon_sitesettings_logo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitesettings',
            old_name='logo',
            new_name='perfume_logo',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='shoe_logo',
            field=models.ImageField(blank=True, null=True, upload_to='site/'),
        ),
    ]
