# Generated by Django 5.2.1 on 2026-07-17 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='banner_type',
            field=models.CharField(choices=[('slider', 'اسلایدر اصلی'), ('collection', 'کالکشن')], default='slider', max_length=20),
        ),
    ]
