# Generated by Django 5.2.1 on 2026-07-17 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_banner_banner_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='layout',
            field=models.CharField(choices=[('single', 'اسلاید بزرگ'), ('double', 'اسلاید دو بخشی')], default='single', max_length=20),
        ),
        migrations.AddField(
            model_name='banner',
            name='second_image',
            field=models.ImageField(blank=True, null=True, upload_to='banners/'),
        ),
        migrations.AddField(
            model_name='banner',
            name='second_video',
            field=models.FileField(blank=True, null=True, upload_to='banners/videos/'),
        ),
    ]
