# Generated by Django 5.2.1 on 2026-07-17 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_banner_layout_banner_second_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='section',
            field=models.CharField(choices=[('shoes', 'کفش'), ('perfume', 'عطر و ادکلن')], default='shoes', max_length=20),
        ),
    ]
