# Generated by Django 5.2.1 on 2026-07-18 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_banner_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('completed', models.BooleanField(default=False)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
