# Generated by Django 5.2.1 on 2026-07-18 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0047_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='کد تخفیف')),
                ('discount_type', models.CharField(choices=[('percent', 'درصدی'), ('fixed', 'مبلغ ثابت')], default='percent', max_length=20)),
                ('value', models.PositiveIntegerField()),
                ('minimum_order', models.PositiveIntegerField(default=0, verbose_name='حداقل خرید')),
                ('max_discount', models.PositiveIntegerField(blank=True, null=True, verbose_name='حداکثر تخفیف')),
                ('usage_limit', models.PositiveIntegerField(default=1, verbose_name='تعداد دفعات استفاده')),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
