# Generated by Django 5.2.1 on 2026-07-19 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0051_orderitem_color_orderitem_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='موجودی'),
        ),
    ]
