# Generated by Django 5.2.1 on 2026-07-19 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0052_post_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tracking_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
