# Generated by Django 5.2.1 on 2026-08-04 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0055_remove_address_address_address_alley_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_free_shipping',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_cost',
            field=models.PositiveIntegerField(default=80000),
        ),
    ]
